/* eslint-disable @next/next/no-page-custom-font */
import {NewslettersProvider} from "../context/NewslettersContext"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pulzo Newsletters',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NewslettersProvider>
          {children}
        </NewslettersProvider>
      </body>
    </html>
  );
}
